---
title: "Project Poster"
author: "Steven Hwang"
date: "March 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
Travelers are increasingly using short term vacation rentals as an alternative to traditional hotels for accomodations. The most popular service for short term vacation rentals is Airbnb, a website that lets anybody rent out their room, apartment, or house. Airbnb's popularity has created a potential revenue source for property owners. Homeowners with a spare bedroom now have the option to rent it out on their desired timeline. Apartment building owners now have the option to rent units to travelers instead of long term tenants. Central to the decision to become an Airbnb host is the expected revenue. Individuals will only list their properties on Airbnb if they expect to make above a certain amount of money. A model that predicts the rental price of a unit given its attributes can help potential Airbnb hosts decide whether to rent out their unit. The decision to host, however, is more complicated. Hosts have many choices about how to set up their short term vacation rental unit, and each choice may influence the price they can charge. Using Airbnb data from Amdsterdam, we model how the attributes a host can and cannot control about their Airbnb unit influence the amount they charge. Analysis and Interpretation of the model can help future Airbnb hosts anticipate potential revenue and determine the optimal way to set up their short term vacation rental unit.

## Background

## Methodology & Analysis

## Results
The expected change in log of y with respect to a one-unit increase in x1 holding all other variables at any fixed value

* The results show that most airbnb account settings are significant at the 0.05 level except for bed types and parking. 
* The variable that had the strongest effect on the price per night is renting out the entire property, with a increase in the price per night by 2.24 times when compared to renting out a shared room while controlling for others.
* An interesting conclusion found was that smoking did not seem to have an affect on the price per night as the coeffecient is close to 1.

|                          |$\beta$   |exp($\beta$)    | SE    | p-value  |
|-------------------------|--------|--------------|-------|----------|
| Intercept               | 2.680  | 14.59       | 0.092 | < 2e-16  |
| Host is superhost       | 0.070  | 1.07        | 0.009 | 4.86e-14 |
| Room type: Private      | 0.397  | 1.49        | 0.008 | < 2e-16  |
| Room type: Entire Place | 0.806  | 2.24        | 0.045 | < 2e-16  |
| Accomodates             | 0.076  | 1.08        | 0.004 | < 2e-16  |
| # of Beds               | 0.006  | 1.01        | 0.004 | 0.0984   |
| Bed type: Couch         | 0.184  | 1.20        | 0.112 | 0.0997   |
| Bed type: Real Bed      | 0.076  | 1.08        | 0.076 | 0.1208   |
| Guest included          | 0.015  | 1.02        | 0.003 | 5.75e-07 |
| Minimum nights          | -0.019 | 0.98        | 0.002 | < 2e-16  |
| Wifi                    | 0.137  | 1.14        | 0.020 | 2.52e-12 |
| Parking                 | 0.019  | 1.02        | 0.013 | 0.1415   |
| Smoking                 | -0.024 | 0.98        | 0.009 | 0.0109   |

## Discussion
Given the attributes of an Airbnb unit, we are able to accurately predict the price per night with a $() root mean square error rate on a validation set. Our model is useful in useful in guiding hosts set up their unit; superhost, room type, accomodates, guests included, minimum nights, wifi, and smoking are all significant variables in our model at the 95% confidence level. The model shows the following: 

Becoming a superhost increases the average price per night by seven percent; hosts should attempt to fulfill the requirements of a superhost. As compared to a shared space, a private room raises the price per night by 50%, and an entire place raises the price 120%; depending on the property, this information can be used to optimize the configuration of an Airbnb rental. Each additional person a unit accommodates raises the price by 7.8% on average, so high density units may be worthwhile. Hosts that require a minimum number of nights charge less for their units, so if the work between stays is minimal, the model suggestions that hosts should not impose a minimum nights requirement. Units with wifi charge around 15% more on average; this information can be used by hosts to decide whether to purchase wifi for their unit. Lastly, units that allow smoking charge less per night, so the model does not indicate that hosts should allow this. 

It must be noted that this analysis does not imply that these attributes are the direct cause on price, as the model is based on observational data, not a randomized experiment. Nonetheless, the coefficients of the model provide useful indications for how hosts should set up their Airbnb units. The model can be improved with more data from locations other than Amsterdam, and more variables of rental units. Interaction effects should be considered, as well as nonlinear models. Regardless, a useful model was produced that provides useful insight into Airbnb vacation rentals.